import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';

import type { DB } from './db';
import { handoffPath } from './paths';
import { buildBrief } from './recall';
import type { Workspace } from './schema';
import { listItems, recentSessions } from './store';

export interface HandoffOptions {
    branch?: string | null;
    budgetTokens?: number;
    /** Write to disk. When false the markdown is returned without side effects. */
    write?: boolean;
    path?: string;
}

/**
 * A checked-in, human-readable handoff document.
 *
 * The SQLite store is the system of record, but a file has properties a database
 * does not: it survives the store being deleted, it can be read by a harness that
 * has no idea xscs exists (just `cat .xscs/HANDOFF.md`), it diffs in review, and
 * it can be committed so a *teammate's* agent starts warm. This is the
 * "reconstruct from a structured handoff file" step that full context resets
 * depend on — the thing you hand a fresh agent when its window is gone.
 */
export function renderHandoff(db: DB, workspace: Workspace, opts: HandoffOptions = {}): string {
    const brief = buildBrief(db, {
        workspace_id: workspace.id,
        branch: opts.branch ?? null,
        budgetTokens: opts.budgetTokens ?? 2400,
        reason: 'handoff document',
        workspaceName: workspace.name,
    });

    const openThreads = listItems(db, {
        workspace_id: workspace.id,
        status: 'active',
        type: 'open_thread',
        limit: 20,
    });

    const sessions = recentSessions(db, workspace.id, 8);

    const lines: string[] = [];
    lines.push(`# Handoff — ${workspace.name}`);
    lines.push('');
    lines.push(`> Generated by \`xscs\` at ${new Date().toISOString()}. Do not edit by hand — edits are overwritten.`);
    lines.push('> To change what appears here, curate the store (\`xscs review\`, \`xscs pin\`, or the dashboard).');
    lines.push('');

    if (brief.text) {
        lines.push(brief.text);
    } else {
        lines.push('_No durable context recorded for this workspace yet._');
    }

    if (openThreads.length) {
        lines.push('');
        lines.push('## Pick up here');
        for (const thread of openThreads) {
            lines.push(`- [ ] ${thread.title} — ${thread.body.replace(/\s+/g, ' ').slice(0, 300)} (\`${thread.id}\`)`);
        }
    }

    lines.push('');
    lines.push('## Recent sessions');
    if (!sessions.length) {
        lines.push('_none recorded_');
    } else {
        for (const s of sessions) {
            const when = new Date(s.started_at).toISOString().replace('T', ' ').slice(0, 16);
            const dur = s.ended_at ? `${Math.round((s.ended_at - s.started_at) / 60000)}m` : 'open';
            lines.push(
                `- \`${when}\` **${s.agent}** ${s.title ?? '(untitled)'} — ${s.prompt_count} prompts, ${s.turn_count} turns, ${dur}${
                    s.git_branch ? `, branch \`${s.git_branch}\`` : ''
                }`,
            );
        }
    }

    lines.push('');
    const text = lines.join('\n');

    if (opts.write !== false) {
        const target = opts.path ?? handoffPath(workspace.root);
        mkdirSync(dirname(target), { recursive: true });
        writeFileSync(target, text, 'utf8');
    }
    return text;
}
